name = "2s-contact-rate-limiter"
main = "index.mjs"
compatibility_date = "2026-10-05"

[durable_objects]
bindings = [
  { name = "CONTACT_RATE_LIMITER", class_name = "ContactRateLimiter" }
]

[exports.ContactRateLimiter]
type = "durable-object"
storage = "sqlite"
